// tipos para agregar los productos
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

// tipos para obtener los productos
export const OBTENER_PRODUCTOS_CARGANDO = "OBTENER_PRODUCTOS_CARGANDO";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

// tipos para eliminar producto
export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const PRODUCTO_ELIMINADO_EXITO = "PRODUCTO_ELIMINADO_EXITO";
export const PRODUCTO_ELIMINADO_ERROR = "PRODUCTO_ELIMINADO_ERROR";

// tipos para eliminar producto
export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const COMENZAR_PRODUCTO_EDICION = "COMENZAR_PRODUCTO_EDICION";
export const PRODUCTO_EDITADO_EXITO = "PRODUCTO_EDITADO_EXITO";
export const PRODUCTO_EDITADO_ERROR = "PRODUCTO_EDITADO_ERROR";
